---
abstract: 'Collection of modules often used by jonasbn'
author:
  - 'Jonas B. Nielsen (jonasbn), <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Bundle: 0.09
dynamic_config: 1
generated_by: 'Module::Build::Bundle version 0.09, CPAN::Meta::Converter version 2.120921'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-JONASBN
provides:
  Task::BeLike::JONASBN:
    file: lib/Task/BeLike/JONASBN.pm
    version: 1.04
requires:
  App::Ack: 0
  App::Prove: 0
  AppConfig: 0
  CPAN::Mini: 0
  CPAN::Reporter: 0
  Class::Accessor: 0
  Cwd: 0
  DBD::Mock: 0
  DBI: 0
  Data::Dumper: 0
  Data::FormValidator: 0
  Date::Calc: 0
  DateTime: 0
  Devel::Cover: 0
  Error: 0
  ExtUtils::Install: 1.47
  File::Copy: 0
  File::Find::Rule: 0
  File::Path: 0
  File::Slurp: 0
  File::Which: 0
  Hash::Merge: 0
  JSON: 0
  List::MoreUtils: 0
  Module::Build: 0.35
  Module::Info::File: 0
  Module::Load: 0
  Params::Validate: 0.85
  Perl::Critic: 0
  Perl::Critic::Bangs: 0
  Perl::Tidy: 0
  Pod::Simple::Wiki: 0
  Spreadsheet::WriteExcel: 0
  TAP::Formatter::JUnit: 0
  Template: 0
  Term::ReadLine::Perl: 0
  Test::Class: 0
  Test::DatabaseRow: 0
  Test::Exception: 0
  Test::Fatal: 0
  Test::Kwalitee: 0
  Test::MockObject::Extends: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
  Test::Prereq: 0
  Tie::IxHash: 0
  Try::Tiny: 0
  WWW::Mechanize: 0
  WWW::Mechanize::Cached: 0
  XML::Simple: 0
  YAML: 0
  YAML::Shell: 0
  local::lib: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Task-BeLike-JONASBN
  homepage: http://logiclab.jira.com/wiki/display/BJONASBN/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/BJONASBN
  x_ProjectChangelog: http://logiclab.jira.com/browse/BJONASBN#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  x_ProjectSite: http://logicLAB.jira.com/browse/BJONASBN
  x_ProjectWiki: http://logiclab.jira.com/wiki/display/BJONASBN/Home
version: 1.04
